import { useState, useEffect } from "react";
import AttendanceReportTable from "../components/AttendanceReportTable";
import { axiosInstance } from "../lib/axios";
import { useAuthStore } from "../store/useAuthStore";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import { Download, FileText } from "lucide-react";
import { useLanguageStore } from "../store/useLanguageStore";

const AttendanceReport = () => {
  const { authUser } = useAuthStore();
  const [attendanceData, setAttendanceData] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const isTeacherOrAdmin = authUser?.role === "teacher" || authUser?.role === "admin";
  const { t } = useLanguageStore();

  useEffect(() => {
    const fetchAttendanceReport = async () => {
      try {
        const res = await axiosInstance.get("/attendance/report");
        if (Array.isArray(res.data)) {
          setAttendanceData(res.data);
        } else {
          setError("Unexpected data format received from server.");
          setAttendanceData([]);
        }
      } catch {
        setError("Failed to fetch attendance report.");
      } finally {
        setLoading(false);
      }
    };

    fetchAttendanceReport();
  }, []);

  if (loading) return <div>Loading attendance report...</div>;
  if (error) return <div>{error}</div>;

  const hasStudentName = attendanceData.length > 0 && attendanceData[0].studentName;

  const exportToPDF = () => {
    const doc = new jsPDF();
    doc.text("Attendance Report", 14, 15);
    
    const tableColumn = hasStudentName ? ["Student", "Class", "Subject", "Date", "Status"] : ["Class", "Subject", "Date", "Status"];
    const tableRows = [];

    attendanceData.forEach(record => {
      const rowData = [
        ...(hasStudentName ? [record.studentName] : []),
        record.className || "N/A",
        record.subjectName || "N/A",
        new Date(record.date).toLocaleDateString(),
        record.status
      ];
      tableRows.push(rowData);
    });

    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 20,
      theme: 'grid',
    });
    
    doc.save("attendance_report.pdf");
  };

  const exportToExcel = () => {
    const tableData = attendanceData.map(record => {
      const row = {};
      if (hasStudentName) row["Student Name"] = record.studentName;
      row["Class"] = record.className || "N/A";
      row["Subject"] = record.subjectName || "N/A";
      row["Date"] = new Date(record.date).toLocaleDateString();
      row["Status"] = record.status;
      return row;
    });

    const worksheet = XLSX.utils.json_to_sheet(tableData);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, "AttendanceReport");
    XLSX.writeFile(workbook, "attendance_report.xlsx");
  };

  const exportClassReportPDF = () => {
    const doc = new jsPDF();
    const className = authUser?.classId?.name || "Class";
    doc.setFontSize(18);
    doc.text(`${className} - Attendance Report`, 14, 15);
    doc.setFontSize(10);
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 14, 22);
    doc.text(`Generated by: ${authUser?.name} (${authUser?.role})`, 14, 28);

    // Summary
    const totalRecords = attendanceData.length;
    const presentCount = attendanceData.filter(r => r.status === "Present").length;
    const absentCount = attendanceData.filter(r => r.status === "Absent").length;
    const attendanceRate = totalRecords > 0 ? ((presentCount / totalRecords) * 100).toFixed(1) : 0;

    doc.setFontSize(12);
    doc.text(`Summary: ${totalRecords} records | ${presentCount} Present | ${absentCount} Absent | ${attendanceRate}% Rate`, 14, 36);

    const tableColumn = hasStudentName 
      ? ["Student", "Class", "Subject", "Date", "Status"] 
      : ["Class", "Subject", "Date", "Status"];
    const tableRows = attendanceData.map(record => [
      ...(hasStudentName ? [record.studentName] : []),
      record.className || "N/A",
      record.subjectName || "N/A",
      new Date(record.date).toLocaleDateString(),
      record.status
    ]);

    autoTable(doc, {
      head: [tableColumn],
      body: tableRows,
      startY: 42,
      theme: 'grid',
      headStyles: { fillColor: [30, 30, 30], textColor: [255, 255, 255] },
      alternateRowStyles: { fillColor: [245, 245, 245] },
    });

    doc.save(`${className}_class_report.pdf`);
  };

  return (
    <div className="glass-card flex flex-col gap-6 max-w-6xl mx-auto w-full">
      <div className="flex justify-between items-center mb-2 flex-wrap gap-4">
        <h2 className="text-3xl font-bold tracking-wide text-white drop-shadow-md">{t("attendanceReport")}</h2>
        {attendanceData.length > 0 && (
          <div className="flex gap-2 flex-wrap">
            {/* PDF Report - available for all */}
            <button 
              onClick={exportToPDF}
              className="glass-button text-xs py-2 px-4 flex items-center gap-2 bg-red-500/20 hover:bg-red-500 text-red-200 hover:text-white border-red-500/20"
            >
              <FileText className="w-4 h-4" /> {t("downloadPDF")}
            </button>

            {/* Excel & Class Report - Only for teachers and admins */}
            {isTeacherOrAdmin && (
              <>
                <button 
                  onClick={exportToExcel}
                  className="glass-button text-xs py-2 px-4 flex items-center gap-2 bg-emerald-500/20 hover:bg-emerald-500 text-emerald-200 hover:text-white border-emerald-500/20"
                >
                  <Download className="w-4 h-4" /> {t("downloadExcel")}
                </button>
                <button 
                  onClick={exportClassReportPDF}
                  className="glass-button text-xs py-2 px-4 flex items-center gap-2 bg-blue-500/20 hover:bg-blue-500 text-blue-200 hover:text-white border-blue-500/20"
                >
                  <FileText className="w-4 h-4" /> {t("classReport")}
                </button>
              </>
            )}
          </div>
        )}
      </div>
      {attendanceData.length === 0 ? (
        <p className="text-neutral-400 font-medium">{t("noData")}</p>
      ) : (
        <AttendanceReportTable attendanceRecords={attendanceData} />
      )}
    </div>
  );
};

export default AttendanceReport;
